name: "HomeAssistant Growatt Local Server"
description: "Local server for listening Shinelink-X datalogger of Growatt"
version: "1.1.0"
slug: "hello_world"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  5279/tcp: 5279